spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thesis_db?useUnicode=true&serverTimezone=UTC&useSSL=false
    username: root
    password: texttext
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

someParameter:
  value: 5463

apinit:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005