spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/thesis_db?useUnicode=true&serverTimezone=UTC&useSSL=false
    username: root
    password: texttext
  jpa:
    #show_sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.yandex.ru
    username: miaki24@yandex.ru
    password: xptdprhcrynedguv
    port: 465
    protocol: smtps
    debug: true

someParameter:
  value: 5463

apinit:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005